### ISSUE TITLE
Illegal Byte Sequence Error on macOS

### ISSUE THREAD

**Issue by alexanderkiel** [itcr-uni-luebeck/fhir-populator#1]
I'm on Catalina and have installed Python 3.9.5 using Homebrew. I created the venv as described in the README. The output is:

```text
(.venv) fhir-populator $ python -m fhir_populator --endpoint http://localhost:8080/fhir --get-dependencies --package de.gecco
[20:49:45] INFO      - endpoint : http://localhost:8080/fhir                                                                                                         populator.py:181
           INFO      - authorization_header : None                                                                                                                   populator.py:181
           INFO      - log_file : None                                                                                                                               populator.py:181
           INFO      - get_dependencies : True                                                                                                                       populator.py:181
           INFO      - non_interactive : False                                                                                                                       populator.py:181
           INFO      - include_examples : False                                                                                                                      populator.py:181
           INFO      - log_level : INFO                                                                                                                              populator.py:181
           INFO      - rewrite_versions : False                                                                                                                      populator.py:181
           INFO      - only_put : False                                                                                                                              populator.py:181
           INFO      - versioned_ids : False                                                                                                                         populator.py:181
           INFO      - exclude_resource_type : None                                                                                                                  populator.py:181
           INFO      - registry_url : https://packages.simplifier.net                                                                                                populator.py:181
           INFO      - packages : ['de.gecco']                                                                                                                       populator.py:181
           INFO     Downloading package with spec de.gecco@1.0.4                                                                                                     populator.py:288
[20:49:46] INFO     Downloading package with spec de.medizininformatikinitiative.kerndatensatz.medikation@1.0.8                                                      populator.py:288
           INFO     Downloading package with spec de.medizininformatikinitiative.kerndatensatz.prozedur@1.0.7                                                        populator.py:288
[20:49:47] INFO     Downloading package with spec de.medizininformatikinitiative.kerndatensatz.laborbefund@1.0.5                                                     populator.py:288
[20:49:48] INFO     Downloading package with spec de.medizininformatikinitiative.kerndatensatz.diagnose@1.0.4                                                        populator.py:288
[20:49:49] INFO     Downloading package with spec hl7.fhir.uv.ips@1.0.0                                                                                              populator.py:288
           INFO     Downloading package with spec de.medizininformatikinitiative.kerndatensatz.meta@1.0.3                                                            populator.py:288
           INFO     Downloading package with spec de.basisprofil.r4@0.9.13                                                                                           populator.py:288
           INFO     Downloading package with spec kbv.basis@1.1.3                                                                                                    populator.py:288
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/akiel/fhir-populator/.venv/lib/python3.9/site-packages/fhir_populator/__main__.py", line 4, in <module>
    Populator().populate()
  File "/Users/akiel/fhir-populator/.venv/lib/python3.9/site-packages/fhir_populator/populator.py", line 351, in populate
    dependency_graph = self.download_packages(packages)
  File "/Users/akiel/fhir-populator/.venv/lib/python3.9/site-packages/fhir_populator/populator.py", line 289, in download_packages
    package_path = self.download_untar_package(package_name=package)
  File "/Users/akiel/fhir-populator/.venv/lib/python3.9/site-packages/fhir_populator/populator.py", line 332, in download_untar_package
    download_tar_fs.extractall(extract_path)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tarfile.py", line 2036, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tarfile.py", line 2077, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tarfile.py", line 2150, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tarfile.py", line 2191, in makefile
    with bltn_open(targetpath, "wb") as target:
OSError: [Errno 92] Illegal byte sequence: '/var/folders/gg/_48t_zj16b53c2vl04s52cjr0000gn/T/fhir-populator0j0pw0l2/extract/kbv.basis_1.1.3/package/examples/Patient - Ludger K\udcfdnigstein.json'
```

The FHIR server is Blaze but it didn't receive any request.

**Comment by jpwiedekopf** [comment]
Hi Alex! The problem seems to arise due to an "ö" being present in the name of the file `kbv.basis_1.1.3/package/examples/Patient - Ludger Königsstein.json`.

I did notice that, and it created some other problems on Fedora as well (mainly because the name couldn't be printed to the terminal using the logging framework). However, this issue happens in the `untar` command that extracts the FHIR package, which didn't happen on Linux for me, but is also happening on my personal Mac (Big Sur, Python 3.8.9 via MacPorts). So we'll likely have to find a different method of extracting the files in the package, at least for Mac users. I'll take a look!

Also, I think that the KBV might want to change the name of the file in the package itself, Umlauts are not a good idea in file names. I'll write an e-mail to that effect.

**Comment by alexanderkiel** [comment]
As macOS is a BSD, some tools are not the GNU tools. For tar this is the case:

macOS:
```text
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
```

Linux:
```text
tar (GNU tar) 1.30
```

Not using umlauts is certainly a good idea.

**Comment by jpwiedekopf** [comment]
Absolutely! bsdtar seems to handle this differently to GNU tar on my Linux machine. However, I believe that `tarfile` in Python implements the needed operations itself and doesn't rely on the tar binary on the PATH.

I've just uploaded a fix (#3), can you perhaps test it before I release a new version?

```
git clone https://github.com/itcr-uni-luebeck/fhir-populator.git
cd fhir-populator
python -m venv venv
source venv/bin/activate
pip install .
python -m fhir_populator --endpoint http://localhost:8080/fhir --get-dependencies --package kbv.basis
```

Works for me on Linux and Big Sur!

**Comment by alexanderkiel** [comment]
Works for me too.

**Comment by jpwiedekopf** [comment]
Great!
